services:
  espidf:
    image: espressif/idf:release-v5.5
    container_name: espidf_dev
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - .:/workspace
